spring:
  application:
    name: itoken-zuul
  boot:
    admin:
      client:
        url: http://120.79.213.52:8084
  zipkin:
    base-url: http://120.79.213.52:9411

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://120.79.213.52:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info