spring:
  application:
    name: itoken-config
  boot:
    admin:
      client:
        url: http://120.79.213.52:8084
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/itokenKKKKK/itoken-config.git
          search-paths: respo
          username: sklkkk
          password: 14371437a.
  zipkin:
    base-url: http://120.79.213.52:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://120.79.213.52:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info